{
 "cells": [
  {
   "cell_type": "code",
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2024-09-03T16:36:49.820107Z",
     "start_time": "2024-09-03T16:35:44.471158Z"
    }
   },
   "source": "pip install tensorflow==1.15.0",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow==1.15.0\r\n",
      "  Downloading tensorflow-1.15.0-cp37-cp37m-macosx_10_11_x86_64.whl (124.0 MB)\r\n",
      "\u001B[K     |████████████████████████████████| 124.0 MB 430 kB/s eta 0:00:011    |█████████████████████████▉      | 100.2 MB 9.5 MB/s eta 0:00:03MB/s eta 0:00:02\r\n",
      "\u001B[?25hRequirement already satisfied: wrapt>=1.11.1 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from tensorflow==1.15.0) (1.14.1)\r\n",
      "Requirement already satisfied: six>=1.10.0 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from tensorflow==1.15.0) (1.16.0)\r\n",
      "Collecting gast==0.2.2\r\n",
      "  Downloading gast-0.2.2.tar.gz (10 kB)\r\n",
      "Collecting tensorflow-estimator==1.15.1\r\n",
      "  Downloading tensorflow_estimator-1.15.1-py2.py3-none-any.whl (503 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 503 kB 13.3 MB/s eta 0:00:01\r\n",
      "\u001B[?25hCollecting absl-py>=0.7.0\r\n",
      "  Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 133 kB 13.1 MB/s eta 0:00:01\r\n",
      "\u001B[?25hCollecting astor>=0.6.0\r\n",
      "  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)\r\n",
      "Collecting google-pasta>=0.1.6\r\n",
      "  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 57 kB 8.9 MB/s  eta 0:00:01\r\n",
      "\u001B[?25hCollecting grpcio>=1.8.6\r\n",
      "  Downloading grpcio-1.62.3-cp37-cp37m-macosx_10_10_universal2.whl (10.0 MB)\r\n",
      "\u001B[K     |████████████████████████████████| 10.0 MB 8.9 MB/s eta 0:00:01    |▌                               | 143 kB 8.9 MB/s eta 0:00:02     |██▍                             | 757 kB 8.9 MB/s eta 0:00:02\r\n",
      "\u001B[?25hCollecting keras-applications>=1.0.8\r\n",
      "  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 50 kB 8.0 MB/s eta 0:00:011\r\n",
      "\u001B[?25hCollecting keras-preprocessing>=1.0.5\r\n",
      "  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 42 kB 3.4 MB/s  eta 0:00:01\r\n",
      "\u001B[?25hCollecting numpy<2.0,>=1.16.0\r\n",
      "  Downloading numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)\r\n",
      "\u001B[K     |████████████████████████████████| 16.9 MB 10.3 MB/s eta 0:00:01\r\n",
      "\u001B[?25hCollecting opt-einsum>=2.3.2\r\n",
      "  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 65 kB 7.1 MB/s  eta 0:00:01\r\n",
      "\u001B[?25hCollecting protobuf>=3.6.1\r\n",
      "  Downloading protobuf-4.24.4-cp37-abi3-macosx_10_9_universal2.whl (409 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 409 kB 11.7 MB/s eta 0:00:01\r\n",
      "\u001B[?25hCollecting tensorboard<1.16.0,>=1.15.0\r\n",
      "  Downloading tensorboard-1.15.0-py3-none-any.whl (3.8 MB)\r\n",
      "\u001B[K     |████████████████████████████████| 3.8 MB 11.2 MB/s eta 0:00:01\r\n",
      "\u001B[?25hRequirement already satisfied: setuptools>=41.0.0 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.0) (51.1.1)\r\n",
      "Collecting markdown>=2.6.8\r\n",
      "  Downloading Markdown-3.4.4-py3-none-any.whl (94 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 94 kB 5.3 MB/s  eta 0:00:01\r\n",
      "\u001B[?25hRequirement already satisfied: importlib-metadata>=4.4 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.0) (4.12.0)\r\n",
      "Requirement already satisfied: typing-extensions>=3.6.4 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.0) (4.3.0)\r\n",
      "Requirement already satisfied: zipp>=0.5 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.0) (3.8.0)\r\n",
      "Collecting termcolor>=1.1.0\r\n",
      "  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)\r\n",
      "Collecting werkzeug>=0.11.15\r\n",
      "  Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 233 kB 12.5 MB/s eta 0:00:01\r\n",
      "\u001B[?25hRequirement already satisfied: MarkupSafe>=2.1.1 in /Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages (from werkzeug>=0.11.15->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.0) (2.1.5)\r\n",
      "Collecting wheel>=0.26\r\n",
      "  Downloading wheel-0.42.0-py3-none-any.whl (65 kB)\r\n",
      "\u001B[K     |████████████████████████████████| 65 kB 5.0 MB/s  eta 0:00:01\r\n",
      "\u001B[?25hCollecting h5py\r\n",
      "  Downloading h5py-3.8.0-cp37-cp37m-macosx_10_9_x86_64.whl (3.2 MB)\r\n",
      "\u001B[K     |████████████████████████████████| 3.2 MB 9.3 MB/s eta 0:00:01\r\n",
      "\u001B[?25hUsing legacy 'setup.py install' for gast, since package 'wheel' is not installed.\r\n",
      "Installing collected packages: numpy, wheel, werkzeug, protobuf, markdown, h5py, grpcio, absl-py, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras-applications, google-pasta, gast, astor, tensorflow\r\n",
      "    Running setup.py install for gast ... \u001B[?25ldone\r\n",
      "\u001B[?25hSuccessfully installed absl-py-2.1.0 astor-0.8.1 gast-0.2.2 google-pasta-0.2.0 grpcio-1.62.3 h5py-3.8.0 keras-applications-1.0.8 keras-preprocessing-1.1.2 markdown-3.4.4 numpy-1.21.6 opt-einsum-3.3.0 protobuf-4.24.4 tensorboard-1.15.0 tensorflow-1.15.0 tensorflow-estimator-1.15.1 termcolor-2.3.0 werkzeug-2.2.3 wheel-0.42.0\r\n",
      "\u001B[33mWARNING: You are using pip version 20.3.3; however, version 24.0 is available.\r\n",
      "You should consider upgrading via the '/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "execution_count": 2
  },
  {
   "metadata": {
    "jupyter": {
     "is_executing": true
    },
    "ExecuteTime": {
     "start_time": "2024-09-03T16:37:01.504118Z"
    }
   },
   "cell_type": "code",
   "source": "import tensorflow as tf\n",
   "id": "2388bd94d0035aab",
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/p7/jn1xlf5518b409x8nbzc5r2w0000gn/T/ipykernel_56047/1482888479.py\", line 1, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 99, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1019, in _handle_fromlist\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py\", line 52, in <module>\n",
      "    from tensorflow.core.framework.graph_pb2 import *\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/node_def_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/attr_value_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/resource_handle_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n",
      "    serialized_options=None, file=DESCRIPTOR),\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py\", line 561, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 33, in <module>\n",
      "    from tensorflow._api.v1 import audio\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/_api/v1/audio/__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_audio_ops.py\", line 11, in <module>\n",
      "    from tensorflow.python.eager import context as _context\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py\", line 29, in <module>\n",
      "    from tensorflow.core.protobuf import config_pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/protobuf/config_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import cost_graph_pb2 as tensorflow_dot_core_dot_framework_dot_cost__graph__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/cost_graph_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n",
      "    serialized_options=None, file=DESCRIPTOR),\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py\", line 561, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/p7/jn1xlf5518b409x8nbzc5r2w0000gn/T/ipykernel_56047/1482888479.py\", line 1, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 99, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1019, in _handle_fromlist\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py\", line 52, in <module>\n",
      "    from tensorflow.core.framework.graph_pb2 import *\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/node_def_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/attr_value_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/resource_handle_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n",
      "    serialized_options=None, file=DESCRIPTOR),\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py\", line 561, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2102, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 33, in <module>\n",
      "    from tensorflow._api.v1 import audio\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/_api/v1/audio/__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_audio_ops.py\", line 11, in <module>\n",
      "    from tensorflow.python.eager import context as _context\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py\", line 29, in <module>\n",
      "    from tensorflow.core.protobuf import config_pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/protobuf/config_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import cost_graph_pb2 as tensorflow_dot_core_dot_framework_dot_cost__graph__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/cost_graph_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n",
      "    serialized_options=None, file=DESCRIPTOR),\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py\", line 561, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/p7/jn1xlf5518b409x8nbzc5r2w0000gn/T/ipykernel_56047/1482888479.py\", line 1, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 99, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1019, in _handle_fromlist\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py\", line 52, in <module>\n",
      "    from tensorflow.core.framework.graph_pb2 import *\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/node_def_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/attr_value_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/resource_handle_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n",
      "    serialized_options=None, file=DESCRIPTOR),\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py\", line 561, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2102, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3258, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2102, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 33, in <module>\n",
      "    from tensorflow._api.v1 import audio\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/_api/v1/audio/__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_audio_ops.py\", line 11, in <module>\n",
      "    from tensorflow.python.eager import context as _context\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py\", line 29, in <module>\n",
      "    from tensorflow.core.protobuf import config_pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/protobuf/config_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import cost_graph_pb2 as tensorflow_dot_core_dot_framework_dot_cost__graph__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/cost_graph_pb2.py\", line 16, in <module>\n",
      "    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py\", line 42, in <module>\n",
      "    serialized_options=None, file=DESCRIPTOR),\n",
      "  File \"/Users/urs/development/gitlab/coin/cfn-redshift-provider/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py\", line 561, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n"
     ]
    }
   ],
   "execution_count": null
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": "model = tf.keras.models.load_model('/Users/urs/development/github/ai/kotlindl/notebook/my-models/mobilenet_with_additional_training')",
   "id": "4c639cbd4994a1f6"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
